# Generated by Django 5.1.7 on 2025-03-10 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('postcode', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('house_type', models.CharField(blank=True, max_length=50)),
                ('occupants', models.PositiveIntegerField(default=1)),
                ('house_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, default='£', max_length=5)),
                ('ownership_proof', models.FileField(blank=True, null=True, upload_to='property_docs/')),
                ('insurance_proof', models.FileField(blank=True, null=True, upload_to='property_docs/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='core.user')),
            ],
        ),
    ]
