# Generated by Django 5.1.7 on 2025-03-11 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
