# Generated by Django 5.1.7 on 2025-03-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='disaster_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='claim',
            name='policy_id',
            field=models.CharField(blank=True, max_length=66),
        ),
    ]
