# Generated by Django 5.1.7 on 2025-03-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_claim_disaster_type_alter_claim_policy_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='estimated_payout',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='final_payout',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
