# Generated by Django 5.1.7 on 2025-03-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_claim_disaster_type_alter_claim_policy_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='riskLevel',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
