# Generated by Django 5.1.7 on 2025-03-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_claim_estimated_payout_claim_final_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='riskLevel',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
