# Generated by Django 5.1.7 on 2025-03-14 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_property_risklevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewDecision',
            fields=[
                ('decision_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('LITTLE_NONE', 'Little/None'), ('MIDDLE', 'Middle'), ('SEVERE', 'Severe')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.TextField()),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.claim')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.employee')),
            ],
        ),
    ]
