# Generated by Django 5.1.7 on 2025-03-14 15:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_reviewdecision_claimreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimreview',
            name='reviewed_at',
        ),
        migrations.AddField(
            model_name='claim',
            name='date_submitted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='claim',
            name='manuel_review',
            field=models.BooleanField(default=False),
        ),
    ]
