# Generated by Django 5.1.7 on 2025-03-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_claimreview_reviewed_at_claim_date_submitted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('REVIEWER', 'Reviewer'), ('ADMIN', 'Admin')], default='USER', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('REVIEWER', 'Reviewer'), ('ADMIN', 'Admin')], default='REVIEWER', max_length=20),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
