# Generated by Django 5.1.7 on 2025-03-18 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_property_risklevel'),
        ('core', '0010_alter_user_role_alter_employee_role_delete_role'),
    ]

    operations = [
    ]
