# Generated by Django 5.1.7 on 2025-03-18 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_property_ethhousevalue_property_ethhousevalue1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='ethHouseValue1',
        ),
    ]
